<?php
session_start();

include '../Connection/init.php';

if (isset($_GET['OrderID'])) { 
    $orderId = $_GET['OrderID'];

    $orderStmt = $db->prepare("SELECT * FROM `order data` WHERE OrderID = :orderId");
    $orderStmt->bindParam(':orderId', $orderId);
    $orderStmt->execute();
    $orderData = $orderStmt->fetch();

    $trackStmt = $db->prepare("SELECT * FROM `trackorder` WHERE OrderID = :orderId");
    $trackStmt->bindParam(':orderId', $orderId);
    $trackStmt->execute();
    $trackData = $trackStmt->fetch();
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Tracked Order</title>
    <link rel="stylesheet" href="../css/TO.css">
</head>
<body>
    <h1>Tracked Order: <?php echo $orderId; ?></h1>

    <h2>Order Data:</h2>
    <ul>
        <li>Order ID: <?php echo $orderData['OrderID']; ?></li>
        <li>Status: <?php echo $orderData['Status']; ?></li>
        <!-- Add more order data fields as needed -->
    </ul>

    <h2>Track Order Data:</h2>
    <ul>
        <li>Order ID: <?php echo $trackData['OrderID']; ?></li>
        <li> <?php echo $orderData['Status']; ?> Order Date: <?php echo $trackData['CompleteOrderDate']; ?></li>
        <!-- Add more track order data fields as needed -->
    </ul>
    <div class="container">
        <div class="order-timeline">
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Order Processed</h2>
                    <p>00 E</p>
                </div>
            </div>
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Order Designing</h2>
                    <p>2020-05-27 11:26:08 AM REQUEST CREATED</p>
                </div>
            </div>
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Order Shipped</h2>
                    <p>Expected Arrival 01/06/20</p>
                </div>
            </div>
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Grasshoppers V534HB</h2>
                </div>
            </div>
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Order En Route</h2>
                    <p>2020-06-04 06:59:48 AM ATTEMPT 1 COMPLETED. ~ ***[AUTO GENERATED BY GRASSHOPPERS]***</p>
                </div>
            </div>
            <div class="timeline-event">
                <div class="event-content">
                    <h2>Order Arrived</h2>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<?php if ($trackData !== null) { ?>
    <ul  style="list-style-type: none;">
        <li>
            <?php echo $orderData['OrderDate']; ?>
            <span class="status-icon">&#10003;</span>
            Order Created
        </li>
        <?php if ($orderData['Status'] === 'Confirmed') { ?>
            <li>
                <?php echo $trackData['ConfirmedDate']; ?>
                <span class="status-icon">&#10003;</span>
                Order Confirmed
            </li>
        <?php } ?>
        <?php if ($orderData['Status'] === 'Processing') { ?>
            <li>
                <?php echo $trackData['ProcessingDate']; ?>
                <span class="status-icon">&#10003;</span>
                Order Processed
            </li>
        <?php } ?>
        <?php if ($orderData['Status'] === 'Ready to Pickup') { ?>
            <li>
                <?php echo $trackData['ReadyToPickUpDate']; ?>
                <span class="status-icon">&#10003;</span>
                Order Ready for Pickup
            </li>
        <?php } ?>
        <?php if ($orderData['Status'] === 'Out for Delivery') { ?>
            <li>
                <?php echo $trackData['OutForDeliveryDate']; ?>
                <span class="status-icon">&#10003;</span>
                Order Out for Delivery
            </li>
        <?php } ?>
        <?php if ($orderData['Status'] === 'Completed') { ?>
            <li>
                <?php echo $trackData['CompleteOrderDate']; ?>
                <span class="status-icon">&#10003;</span>
                Order Completed
            </li>
        <?php } ?>
    </ul>
<?php } ?>